---
- name: Create dependant groups if they don't exist 
  # FIXME does this matter if it's not a rasp pi?
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - video
    - audio
    - render

- name: Create plexamp user and home directory
  # FIXME same here, does the user need these groups?
  ansible.builtin.user:
    name: "{{ plexamp_user }}"
    shell: /bin/bash
    groups:
      - video
      - audio
      - render
    uid: "{{ plexamp_uid }}"

- name: Create directory for Plexamp Headless
  ansible.builtin.file:
    dest: "/home/{{plexamp_user}}/plexamp"
    owner: "{{ plexamp_user }}"
    group: "{{ plexamp_group }}"
    state: directory 
